// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVU6KuNjE1iIcSb_5uI96yCF6jIqI-3GQ',
    appId: '1:339364873947:android:282712b53bd22ca5d3eefe',
    messagingSenderId: '339364873947',
    projectId: 'celes-movie-booking-ticket',
    storageBucket: 'celes-movie-booking-ticket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQOlY2km6vB8y2hzwMoB3aHsJmg2vwLM',
    appId: '1:339364873947:ios:45efe4d3734ca6e9d3eefe',
    messagingSenderId: '339364873947',
    projectId: 'celes-movie-booking-ticket',
    storageBucket: 'celes-movie-booking-ticket.firebasestorage.app',
    iosBundleId: 'com.celes.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQOlY2km6vB8y2hzwMoB3aHsJmg2vwLM',
    appId: '1:339364873947:ios:45efe4d3734ca6e9d3eefe',
    messagingSenderId: '339364873947',
    projectId: 'celes-movie-booking-ticket',
    storageBucket: 'celes-movie-booking-ticket.firebasestorage.app',
    iosBundleId: 'com.celes.app',
  );
}
